package com.vthr.erp_hrm.core.model;

public enum NotificationType {
    APPLICATION_STAGE_CHANGED,
    INTERVIEW_SCHEDULED,
    APPLICATION_TASK_ASSIGNED,
    APPLICATION_TASK_REVIEWED,
    APPLICATION_TASK_DOCUMENT_UPLOADED,
    APPLICATION_UPDATED,
    OTHER
}

