spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres_db:5432/erp_hrm}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:redis_cache}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

spring.jpa.hibernate.ddl-auto=update
