spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/erp_hrm}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:0000}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

spring.jpa.hibernate.ddl-auto=update
